### ISSUE TITLE
Beverage

### ISSUE THREAD

**Issue by 010Jay** [010Jay/Project362SGroup09Client#3]
Add your entity and factory artifacts which you already have in the backend application. Then add your user interface for your assigned entity and the rest implementation to make the rest requests to the backend.

**Comment by Nonhlahla** [comment]
Ooh yes I have been having trouble with the rest implementation so I will try an look into the food one. With the GuI I am almost done I used the student GUI form so I am left with adding the drop down on it so thanks I will look into the food one also.
